### ISSUE TITLE
Charging ic (MCP73831) getting hot

### ISSUE THREAD

**Issue by raghavendrahassy** [ExploreEmbedded/Hornbill-ESP32-DEV#6]
@ LIPO battery Charging ic (MCP73831) getting hot.
Following changes needs to be done for layout is used as heat sink.
1. Copper pad should be thick.
2. add many vias for heat to dissipate.
3. Cin and Cout cap. should be placed closer to pin.
 Check the below image.
![image](https://cloud.githubusercontent.com/assets/12540595/25522287/f7851d7c-2c1f-11e7-822c-545590f14e7e.png)

**Comment by sharanago** [comment]
Charger circuit layout changed as suggested. Verify if any changes.
